#cloud-config
# Cloud: Hetzner Cloud (though this may work with your cloud without any changes)
# Instance Type: Shared vCPU, CPX11 (2 vCPU, 2GB RAM)
# OS: Ubuntu 22.04
#
# This downloads the latest RouterOS CHR 7.x Stable image, writes it to disk
# (/dev/sda by default--see below), maximizes the main partition, and reboots.
#
runcmd:
  - apt-get update >/dev/tty1 2>&1
  - apt-get install -y ufw curl unzip squashfs-tools xorriso >/dev/tty1 2>&1
  - ufw enable >/dev/tty1 2>&1
  - curl -Ls https://raw.githubusercontent.com/mattx86/routeros-chr-cloud-config/main/install-routeros-chr-7.x-stable.sh -o /root/install-routeros-chr-7.x-stable.sh
  - chmod 700 /root/install-routeros-chr-7.x-stable.sh
  - /root/install-routeros-chr-7.x-stable.sh /dev/sda >/dev/tty1 2>&1